# Created by Spades<spadesge@gmail.com> on 18/09/25

sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

branches:
  - master
  - dev
  
install: 
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent